config/routes.rb
Rails.application.routes.draw do
  root 'musics#playlist'
  get 'register/info1'
  get 'register/info2'
  post 'register/infoget'
  resources :posts do
    post "/like", to: "likes#like_toggle"
  end
  get 'musics/playlist'
  get 'musics/music'
  get 'musics/playlist2'
  post '/posts/:post_id' =>"comments#create"
  post '/posts/:post_id/comments/:comment_id' =>"comments#destroy"
  post '/posts/:post_id/comments/:id' =>"comments#update"
  get 'posts/new'=> 'posts#new'
  post 'posts/posts/show' => "posts#share"
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations", sessions: 'users/sessions'  }
  resources :playlists
  

end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  before_action :set_user, only: [:info1, :info2, :infoget]
  before_filter :authenticate_user!
  def info1
  end

  def info2
  end
  
  def infoget
    # 이메일 있음
    unless @user.email.nil? or @user.email == ''
   
    # 이메일 없음 = kakao
    else
      @user.email = params[:email]
   
    end
    @user.save
    redirect_to musics_playlist_path
  end

  private
  def set_user
    @user = current_user
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/register/info1.html.erb
<% @user = current_user %>

<%= form_tag(register_infoget_path) do %>
  <% if @user.email.nil? or @user.email == '' %>
  <div>
    <div>
      <label for="email" >email</label>
      <%= text_field_tag :email, nil, placeholder: "abc@example.com" %>
    </div>
  <% end %>

    <div>
      <%= submit_tag "제출"%>
<% end %>
    </div>
  </div>

app/views/register/info2.html.erb
<% @user = current_user %>

<%= form_tag(register_infoget_path) do %>
  <% if @user.email.nil? or @user.email == '' %>
  <div>
    <div>
      <label for="email" >email</label>
      <%= text_field_tag :email, nil, placeholder: "abc@example.com" %>
    </div>
  <% end %>

    <div>
      <%= submit_tag "제출"%>
<% end %>
    </div>
  </div>